version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: django-tutorial

        volumes:
            - ./workspace:/workspace
            
            - ./doc:/workspace/doc
            - ./README.md:/workspace/README.md

        ports:
            - 8000:18000

        environment:
            - DJANGO_DEBUG=1

        command: /bin/sh -c "while sleep 1000; do :; done"
