default:

migrate:
	python3 manage.py migrate

makemigrations:
	python3 manage.py makemigrations

superuser:
	python3 manage.py createsuperuser --username admin --email admin@via-internet.de

run:
	python3 manage.py runserver 0.0.0.0:8000
	
